# Generated by Django 5.2 on 2025-06-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0001_initial'),
    ]

    operations = [
       
        # migrations.AddField(
        #     model_name='ventas',
        #     name='total',
        #     field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        # ),
        migrations.AlterField(
            model_name='detallescompras',
            name='idcompra',
            field=models.ForeignKey(db_column='idCompra', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallesCompra', to='sabores.compras'),
        ),
        migrations.AlterField(
            model_name='detallesventas',
            name='idventa',
            field=models.ForeignKey(db_column='idVenta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='detallesVentas', to='sabores.ventas'),
        ),
    ]
