# Generated by Django 5.2 on 2025-07-10 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0002_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='idproveedor',
        ),
        migrations.AlterField(
            model_name='detallescompras',
            name='idcompra',
            field=models.ForeignKey(db_column='idCompra', on_delete=django.db.models.deletion.CASCADE, related_name='detallesCompra', to='sabores.compras'),
        ),
    ]
