# Generated by Django 5.2 on 2025-07-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0003_remove_compras_idproveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescompras',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2025-7-17"),
            preserve_default=False,
        ),
    ]
