# Generated by Django 5.2 on 2025-08-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0004_detallescompras_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
