# Generated by Django 5.2 on 2025-09-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0002_remove_ventas_subtotal_ventas_total_and_more'),
        ('sabores', '0005_categorias_deleted_at_productos_deleted_at_and_more'),
    ]

    operations = [
    ]
