# Generated by Django 5.2.6 on 2025-09-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0006_merge_20250924_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallescompras',
            name='idcompra',
            field=models.ForeignKey(db_column='idCompra', on_delete=django.db.models.deletion.CASCADE, related_name='detallesCompra', to='sabores.compras'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
