# Generated by Django 5.2 on 2025-10-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0007_alter_detallescompras_idcompra_alter_ventas_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='mensaje',
        ),
    ]
