# Generated by Django 5.2 on 2025-10-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0008_remove_notificaciones_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='fecha_de_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
