# Generated by Django 5.2 on 2025-10-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0009_alter_compras_fecha_alter_gastos_fecha_de_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='fecha_de_pago',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
