# Generated by Django 6.0.3 on 2026-03-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0011_ventas_devuelta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Mesa',
                'managed': True,
            },
        ),
    ]
