# Generated by Django 6.0.3 on 2026-03-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0012_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='mesaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sabores.mesa'),
        ),
    ]
