# Generated by Django 5.2 on 2026-04-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0013_ventas_mesaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deudores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('deuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('autorizo_datos', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Deudores',
                'managed': True,
            },
        ),
    ]
