# Generated by Django 5.2 on 2026-04-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0014_deudores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudores',
            old_name='autorizo_datos',
            new_name='autorizacion',
        ),
        migrations.AlterField(
            model_name='deudores',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='deudores',
            table='deudores',
        ),
    ]
