# Generated by Django 5.2 on 2026-04-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0015_rename_autorizo_datos_deudores_autorizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoIngreso', models.CharField(max_length=50)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingresosExternos',
                'managed': True,
            },
        ),
    ]
