# Generated by Django 6.0.3 on 2026-04-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0016_ingresosexternos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesa',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
