# Generated by Django 6.0.3 on 2026-04-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0017_mesa_capacidad_mesa_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='sabores.mesa')),
            ],
            options={
                'db_table': 'Pedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='productoId', on_delete=django.db.models.deletion.PROTECT, to='sabores.productos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sabores.pedido')),
            ],
            options={
                'db_table': 'DetallesPedido',
                'managed': True,
            },
        ),
    ]
