# Generated by Django 6.0.3 on 2026-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0018_pedido_detallespedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='codigoBarras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
