# Generated by Django 6.0.3 on 2026-04-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0020_pedido_proveniencia_alter_pedido_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total_ventas', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_propinas', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_descorches', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_otros', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_ingresos', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_gastos', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_compras', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_egresos', models.DecimalField(decimal_places=0, max_digits=12)),
                ('balance_neto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('conteo_deudores', models.IntegerField()),
                ('deuda_total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('num_ventas', models.IntegerField()),
            ],
            options={
                'db_table': 'CierreCaja',
                'ordering': ['-fecha', '-hora'],
                'managed': True,
            },
        ),
    ]
