# Generated by Django 6.0.3 on 2026-04-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabores', '0021_cierrecaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierrecaja',
            options={'managed': True, 'ordering': ['-fecha']},
        ),
    ]
